// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaMedicoApp.Infra.Data.Context;

#nullable disable

namespace SistemaMedicoApp.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaMedicoApp.Domain.Models.Entities.Exame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEntregaResultado")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAENTREGARESULTADO");

                    b.Property<DateTime>("DataExame")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAEXAME");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("OBSERVACOES");

                    b.Property<int>("SituacaoExame")
                        .HasColumnType("int")
                        .HasColumnName("STATUSEXAME");

                    b.Property<string>("TipoExame")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIPOEXAME");

                    b.HasKey("Id");

                    b.ToTable("EXAME", (string)null);
                });

            modelBuilder.Entity("SistemaMedicoApp.Domain.Models.Entities.ItensPedidoExame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExameId")
                        .HasColumnType("int")
                        .HasColumnName("EXAMEID");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("OBSERVACOES");

                    b.Property<int>("PedidoExameId")
                        .HasColumnType("int")
                        .HasColumnName("PEDIDOEXAMEID");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExameId");

                    b.HasIndex("PedidoExameId");

                    b.ToTable("ITENSPEDIDOEXAME", (string)null);
                });

            modelBuilder.Entity("SistemaMedicoApp.Domain.Models.Entities.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ENDERECO");

                    b.Property<int>("Genero")
                        .HasColumnType("int")
                        .HasColumnName("GENERO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("PACIENTE", (string)null);
                });

            modelBuilder.Entity("SistemaMedicoApp.Domain.Models.Entities.PedidoExame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAPEDIDO");

                    b.Property<int>("ExameId")
                        .HasColumnType("int");

                    b.Property<string>("MedicoSolicitante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MEDICOSOLICITANTE");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("OBSERVACOES");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int")
                        .HasColumnName("PACIENTEID");

                    b.Property<int>("SituacaoPedidoExame")
                        .HasColumnType("int")
                        .HasColumnName("SITUACAOPEDIDOEXAME");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("PEDIDOEXAME", (string)null);
                });

            modelBuilder.Entity("SistemaMedicoApp.Domain.Models.Entities.ItensPedidoExame", b =>
                {
                    b.HasOne("SistemaMedicoApp.Domain.Models.Entities.Exame", "Exame")
                        .WithMany("ItensPedidoExame")
                        .HasForeignKey("ExameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaMedicoApp.Domain.Models.Entities.PedidoExame", "PedidoExame")
                        .WithMany("ItensPedidoExame")
                        .HasForeignKey("PedidoExameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exame");

                    b.Navigation("PedidoExame");
                });

            modelBuilder.Entity("SistemaMedicoApp.Domain.Models.Entities.PedidoExame", b =>
                {
                    b.HasOne("SistemaMedicoApp.Domain.Models.Entities.Paciente", "Paciente")
                        .WithMany("Pedidos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("SistemaMedicoApp.Domain.Models.Entities.Exame", b =>
                {
                    b.Navigation("ItensPedidoExame");
                });

            modelBuilder.Entity("SistemaMedicoApp.Domain.Models.Entities.Paciente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("SistemaMedicoApp.Domain.Models.Entities.PedidoExame", b =>
                {
                    b.Navigation("ItensPedidoExame");
                });
#pragma warning restore 612, 618
        }
    }
}
